apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk054-first-deploy-test
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk054-first-deploy-test
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/prometheus'
        update: 0f4b7aed2c4f3e96663372f1c32704fd
      labels:
        app: sk054-first-deploy-test
    spec:
      serviceAccountName: default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: skala-k8s-practice
                operator: In
                values:
                - "yes"
      volumes:
      - name: skala-config-volume
        configMap:
          name: skala-configmap
      containers:
      - name: webserver
        image: amdp-registry.skala-ai.com/skala25a/sk054-webserver:2.0.0
        imagePullPolicy: Always
        volumeMounts:
        - name: skala-config-volume
          mountPath: /etc/skala
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: USER_NAME
          value: sk054
        - name: SKALA_INFO
          valueFrom:
            configMapKeyRef:
              name: skala-configmap
              key: skala-info
      tolerations:
      - effect: 
        key: skala-k8s-practice
        operator: Equal
        value: "yes"
